@base_url=http://localhost
@token={{login.response.body.token}}

GET {{base_url}}/health/ping

### login 
# @name login
POST {{base_url}}/auth/login 
Content-Type: application/json

{
    "email": "teste@teste.com",
    "password": "123456"
}


### post link endpoint
POST {{base_url}}/links
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "original": "https://sacola.magazineluiza.com.br/?f=1#/cliente/login/?next=https://www.magazineluiza.com.br/lava-e-seca-samsung-wd11t-smart-com-ecobubble-11kg-inox-look/p/dd43eh6he5/ed/ela1/?seller_id=samsung"
}

### redirect link endpoint
GET {{base_url}}/javvl5x

### get all links endpoint
GET {{base_url}}/links/all
Authorization: Bearer {{token}}


